---
- name: Check unpartitioned space
  become: yes
  shell: parted /dev/mmcblk0 unit gb print free | grep 'Free Space' | tail -n1 | awk '{print $3}'
  register: unpartitioned
  changed_when: false
  failed_when: unpartitioned.stderr != ""

- name: Expand root filesystem to fill disk
  become: yes
  command: raspi-config --expand-rootfs
  when: unpartitioned.stdout != "0.00GB"
  notify: "reboot required"
