---
- name: Configure option values in /etc/locale.gen file.
  become: yes
  replace:
    path: /etc/locale.gen
    backup: yes
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  with_items: "{{ locale_options }}"
  register: locale_gen

- name: Generate Locale
  become: yes
  command: locale-gen {{ locale }}
  when: locale_gen is changed

- name: Set Locale
  become: yes
  command: update-locale LC_ALL={{ locale }} LANG={{ locale }}
  when: locale_gen is changed
