# mount external hard drive

# create group to allow permission on mount directory
- name: Create group insignia
  become: yes
  group:
    name: insignia
    state: present

- name: Add user pi to group insignia
  become: yes
  user:
    name: "{{ ansible_ssh_user }}"
    groups: insignia
    append: yes

# create directory for mount point with sticky bit (to preserve group owner)
- name: Create dir wd-my-book with sticky bit
  become: yes
  file:
    path: /mnt/wd-my-book
    owner: pi
    group: insignia
    mode: ug=rwx,o=rx,g+s
    state: directory

# mount external drive
- name: Mount up device in wd-my-book directory
  become: yes
  mount:
    # TODO parameterize uuid, find with sudo blkid
    src: UUID=c76b2505-13cb-43d4-9096-bd5118afe677
    path: /mnt/wd-my-book
    fstype: ext4
    opts: defaults
    state: mounted

- name: home dir symlink to mount dir
  file:
    src: /mnt/wd-my-book
    dest: /home/pi/insignia
    state: link
